version: "3.10"
services:
  db:
    container_name: postgres_container
    image: postgres:15.3
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "m.tex"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d m.tex"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgres

  api:
    container_name: m_tex_api
    build: api/
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres
    environment:
      DB_URI: "postgresql://admin:123456@postgres_container/m.tex"

  client:
    container_name: m_tex_client
    build: client/
    depends_on:
      - api
    networks:
      - postgres
    environment:
      M: "400"
      N: "2"
      URL: "http://m_tex_api:8000/api/data"

  background:
    container_name: m_tex_background
    build: background/
    depends_on:
      - api
    networks:
      - postgres
    environment:
      M: "500"
      N: "3"
      URL: "http://m_tex_api:8000/api/data"
      FILE_MOUNT: "/var/background/file_standart.log"
    volumes:
      - ./data:/var/background


networks:
  postgres:
    driver: bridge